(TeX-add-style-hook "estiloBase"
 (lambda ()
    (TeX-run-style-hooks
     "tikz"
     "graphicx"
     "fullpage"
     "float"
     "eurosym"
     "caption"
     "listings"
     "supertabular"
     "multirow"
     "array"
     "amsmath"
     "amsthm"
     "amssymb"
     "amsfonts"
     "fncychap"
     "Sonny"
     "geometry"
     "hyperref"
     "color"
     "babel"
     "spanish"
     "fontenc"
     "T1"
     "times"
     "inputenc"
     "utf8")))

